---
- name: install epel-release
  yum:
    name: epel-release
    state: present

- name: install openvpn
  yum:
    name: openvpn
    state: present

- name: install iperf
  yum:
    name: iperf           
    state: present

- name: install easy-rsa
  yum:
    name: easy-rsa
    state: present
  when: ansible_hostname == "ovpnserver"

...

